[project]
name = "nafa-py"
version = "0.1.0"
authors = [
    { name = "Bryce Berger", email = "bryce.z.berger@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
