[package]
name = "nafa-io"
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
eyre.workspace = true
ftdi-mpsse = "0.1.2"
ftdi.workspace = true
rusb.workspace = true
strum = { workspace = true, features = ["derive"] }
tracing.workspace = true
