[package]
name = "nafa-io"
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
eyre.workspace = true
rusb.workspace = true
strum = { workspace = true, features = ["derive"] }
tracing.workspace = true

[dev-dependencies]
insta = "1.43.2"
